
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Esta clase es una GUI de inicio de sesion que cuenta con otras ventanas u clases, tales como
 * registrarse y recuperar contraseña, tambien verifica los parametros ingresados y cuenta 
 * con etiquetas de ayuda para los usuarios, entre otras funciones mas.
 * @author Miguel Jesus Zuñiga Coneo
 * @version 2.0
 */
public class Login extends javax.swing.JFrame {


    private String usuario;
    private String correo;
    private String contrasena;

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ForgotPswrd = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        CampoTxtUser = new HintTextField("Ingresa tu usuario");
        Help1 = new javax.swing.JLabel();
        CampoTxtPassword = new HintPasswordField("Ingresa tu contraseña");
        Help2 = new javax.swing.JLabel();
        Help3 = new javax.swing.JLabel();
        RbtnRecuerdame = new javax.swing.JRadioButton();
        Help4 = new javax.swing.JLabel();
        Help6 = new javax.swing.JLabel();
        Registrarme = new javax.swing.JLabel();
        Help5 = new javax.swing.JLabel();
        BtnEnter = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio De Sesion");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ForgotPswrd.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        ForgotPswrd.setForeground(new java.awt.Color(255, 255, 255));
        ForgotPswrd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForgotPswrd.setText("<html><u>¿Olvidaste tu contraseña?</u></html>");
        ForgotPswrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPswrdMouseClicked(evt);
            }
        });
        getContentPane().add(ForgotPswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 170, 20));

        Logo.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/usuario-de-perfil.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 170, 110));

        CampoTxtUser.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        CampoTxtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoTxtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CampoTxtUserFocusLost(evt);
            }
        });
        CampoTxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTxtUserActionPerformed(evt);
            }
        });
        getContentPane().add(CampoTxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 170, 40));

        Help1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        Help1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Help1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/advertencia.png"))); // NOI18N
        Help1.setToolTipText("");
        Help1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Help1MouseClicked(evt);
            }
        });
        getContentPane().add(Help1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 30, 40));

        CampoTxtPassword.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        getContentPane().add(CampoTxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 170, 40));

        Help2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        Help2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Help2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/advertencia.png"))); // NOI18N
        Help2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Help2MouseClicked(evt);
            }
        });
        getContentPane().add(Help2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 30, 40));

        Help3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Help3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Help3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/advertencia (1).png"))); // NOI18N
        Help3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Help3MouseClicked(evt);
            }
        });
        getContentPane().add(Help3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 30, 20));

        RbtnRecuerdame.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        RbtnRecuerdame.setForeground(new java.awt.Color(255, 255, 255));
        RbtnRecuerdame.setText("Recordarme");
        RbtnRecuerdame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RbtnRecuerdameMouseClicked(evt);
            }
        });
        getContentPane().add(RbtnRecuerdame, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 40));

        Help4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Help4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Help4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/advertencia (1).png"))); // NOI18N
        Help4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Help4MouseClicked(evt);
            }
        });
        getContentPane().add(Help4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 30, 40));

        Help6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        Help6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Help6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/advertencia (1).png"))); // NOI18N
        Help6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Help6MouseClicked(evt);
            }
        });
        getContentPane().add(Help6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 30, 40));

        Registrarme.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        Registrarme.setForeground(new java.awt.Color(255, 255, 255));
        Registrarme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registrarme.setText("<html><u>Registrarme</u></html>");
        Registrarme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarmeMouseClicked(evt);
            }
        });
        getContentPane().add(Registrarme, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 90, 20));

        Help5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Help5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Help5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/advertencia (1).png"))); // NOI18N
        Help5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Help5MouseClicked(evt);
            }
        });
        getContentPane().add(Help5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 30, 20));

        BtnEnter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iniciar-sesion (2).png"))); // NOI18N
        BtnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEnterMouseClicked(evt);
            }
        });
        getContentPane().add(BtnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 50, 40));

        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 30, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo1(1).png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ForgotPswrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPswrdMouseClicked
        RecoverPassword obj = new RecoverPassword();
        obj.setVisible(true);
    }//GEN-LAST:event_ForgotPswrdMouseClicked

    private void CampoTxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTxtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTxtUserActionPerformed

    private void CampoTxtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoTxtUserFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTxtUserFocusLost

    private void CampoTxtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoTxtUserFocusGained

    }//GEN-LAST:event_CampoTxtUserFocusGained

    private void Help1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Help1MouseClicked
        JOptionPane.showMessageDialog(this, "En este campo debe ingresar su Usuario\n(Para poder iniciar sesion)");

    }//GEN-LAST:event_Help1MouseClicked

    private void Help2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Help2MouseClicked
        JOptionPane.showMessageDialog(this, "En este campo debe ingresar su Contaseña");
    }//GEN-LAST:event_Help2MouseClicked

    private void Help3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Help3MouseClicked
        JOptionPane.showMessageDialog(this, "Haga click en este campo para recuperar su contraseña\n(En caso de que la haya olvidado)");
    }//GEN-LAST:event_Help3MouseClicked

    private void Help4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Help4MouseClicked
        JOptionPane.showMessageDialog(this, "Haga click para que el programa abra el explorador de archivos y importe sus datos de inicio de sesion\n(debe seleccionar el archivo donde estan estos datos)");
    }//GEN-LAST:event_Help4MouseClicked

    private void Help6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Help6MouseClicked
        JOptionPane.showMessageDialog(this, "Pulse el boton para iniciar sesion");
    }//GEN-LAST:event_Help6MouseClicked

    private void RegistrarmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarmeMouseClicked
        SingUp obj = new SingUp();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistrarmeMouseClicked

    private void Help5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Help5MouseClicked
        JOptionPane.showMessageDialog(this, "Haga click en este campo para registrarse\n(En caso de que sea un usuario nuevo)");
    }//GEN-LAST:event_Help5MouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_CloseMouseClicked

    private void BtnEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEnterMouseClicked
// Si el radio botón está seleccionado
        if (RbtnRecuerdame.isSelected()) {
            // Obtener los datos del radio botón
            String usuario = CampoTxtUser.getText();
            String contraseña = CampoTxtPassword.getText();

            // Validar los datos
            if (!esContrasenaValida(contraseña)) {
                JOptionPane.showMessageDialog(null, "La contraseña debe tener al menos 8 caracteres y contener al menos una letra y un número");
                return;
            }

            // Iniciar sesión
            iniciarSesion(usuario, contraseña);
        } else {
            // Usar el código original
            // Mostrar un mensaje al usuario para que elija el archivo
            JOptionPane.showMessageDialog(this, "Por favor, elija el archivo que contiene sus datos de registro.");

            // Solicitar al usuario el archivo a abrir
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos txt", "txt"));
            int seleccion = fileChooser.showOpenDialog(this);

            if (seleccion == JFileChooser.APPROVE_OPTION) {
                File archivo = fileChooser.getSelectedFile();
                String rutaArchivo = archivo.getAbsolutePath();

                // Obtener los valores de las variables usuario, correo y contrasena
                usuario = CampoTxtUser.getText();
                char[] contrasenaLogin = CampoTxtPassword.getPassword();
                String contrasenaLoginTexto = new String(contrasenaLogin);

                // Validar la contraseña
                if (contrasenaLoginTexto.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Ingrese la contraseña");
                    return;
                } else if (!esContrasenaValida(contrasenaLoginTexto)) {
                    JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 8 caracteres y contener al menos una letra y un número");
                    return;
                }

                // Comprobar si el archivo seleccionado es un archivo txt
                if (!archivo.getName().endsWith(".txt")) {
                    JOptionPane.showMessageDialog(this, "El archivo seleccionado no es un archivo txt.");
                    return;
                }

                // Comprobar si el archivo seleccionado está vacío
                if (archivo.length() == 0) {
                    JOptionPane.showMessageDialog(this, "El archivo seleccionado está vacío.");
                    return;
                }

                // Abrir el archivo txt seleccionado
                try {
                    FileReader lector = new FileReader(archivo);
                    BufferedReader buffer = new BufferedReader(lector);

                    // Leer las líneas del archivo txt
                    String linea;
                    while ((linea = buffer.readLine()) != null) {
                        // Dividir la línea en sus componentes
                        String[] componentes = linea.split(": ");

                        // Validar la contraseña y el usuario
                        if (componentes[0].equals(usuario) && componentes[2].toLowerCase().equals(contrasenaLoginTexto.toLowerCase())) {
                            // El usuario y la contraseña son válidos
                            JOptionPane.showMessageDialog(this, "¡Inicio de sesión exitoso!");
                            return;
                        } 
                    }

                    // El usuario y la contraseña no son válidos
                    JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
                } catch (IOException ex) {
                    ex.printStackTrace();
                }

            }
        }
    }//GEN-LAST:event_BtnEnterMouseClicked
    public void iniciarSesion(String usuario, String contraseña) {
        // Validar el usuario y la contraseña
        if (!esUsuarioValido(usuario)) {
            JOptionPane.showMessageDialog(this, "El usuario no es válido.");
            return;
        }

        if (!esContrasenaValida(contraseña)) {
            JOptionPane.showMessageDialog(this, "La contraseña no es válida.");
            return;
        }

        // Iniciar sesión
        System.out.println("Inicio de sesión exitoso!");

        // Agregar el usuario a la sesión
        // Session.getInstance().setUsuario(usuario);
    }

    public static boolean esUsuarioValido(String usuario) {
        // Verificar que el usuario no esté vacío
        if (usuario.isEmpty()) {
            return false;
        }

        // Verificar que el usuario exista en el sistema
        // TODO: Implementar esta lógica
        return true;
    }
    private void RbtnRecuerdameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RbtnRecuerdameMouseClicked
        // Solicitar al usuario que seleccione el archivo
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos txt", "txt"));
        int seleccion = fileChooser.showOpenDialog(this);

        // Si el usuario seleccionó un archivo
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                // Obtener el archivo seleccionado
                File archivo = fileChooser.getSelectedFile();

                // Extraer los datos del archivo
                String usuario = leerUsuarioArchivo(archivo);
                String contraseña = leerContrasenaArchivo(archivo);

                // Colocar los datos en los campos de texto
                CampoTxtUser.setText(usuario);
                CampoTxtPassword.setText(contraseña);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_RbtnRecuerdameMouseClicked
// Leer el usuario del archivo

    public static String leerUsuarioArchivo(File archivo) throws IOException {
        // Abrir el archivo
        FileReader lector = new FileReader(archivo);
        BufferedReader buffer = new BufferedReader(lector);

        // Leer la primera línea del archivo
        String linea = buffer.readLine();

        // Cerrar el archivo
        buffer.close();
        lector.close();

        // Devolver el usuario
        return linea.split(":")[0];
    }
// Leer la contraseña del archivo

    public static String leerContrasenaArchivo(File archivo) throws IOException {
        // Abrir el archivo
        FileReader lector = new FileReader(archivo);
        BufferedReader buffer = new BufferedReader(lector);

        // Leer la primera línea del archivo
        String linea = buffer.readLine();

        // Cerrar el archivo
        buffer.close();
        lector.close();

        // Devolver la contraseña
        return linea.split(":")[1];
    }

    public boolean esContrasenaValida(String contrasena) {
        if (contrasena.length() < 8) {
            return false;
        }
        boolean tieneLetra = false;
        boolean tieneNumero = false;
        for (int i = 0; i < contrasena.length(); i++) {
            char c = contrasena.charAt(i);
            if (Character.isLetter(c)) {
                tieneLetra = true;
            } else if (Character.isDigit(c)) {
                tieneNumero = true;
            }
        }
        return tieneLetra && tieneNumero;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnEnter;
    private javax.swing.JPasswordField CampoTxtPassword;
    private javax.swing.JTextField CampoTxtUser;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel ForgotPswrd;
    private javax.swing.JLabel Help1;
    private javax.swing.JLabel Help2;
    private javax.swing.JLabel Help3;
    private javax.swing.JLabel Help4;
    private javax.swing.JLabel Help5;
    private javax.swing.JLabel Help6;
    private javax.swing.JLabel Logo;
    private javax.swing.JRadioButton RbtnRecuerdame;
    private javax.swing.JLabel Registrarme;
    // End of variables declaration//GEN-END:variables
}
