
import java.io.*;
import javax.swing.*;
import javax.swing.filechooser.*;
import mail.Validacion;

/**
 * Esta es la clase de registro, funciona para almacenar los datos de registro de los usuarios
 * @author Miguel Jesus Zuñiga Coneo
 * @version 2.0
 */
public class SingUp extends javax.swing.JFrame {

    /**
     * Creates new form SingUp
     */
    public SingUp() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegistro = new javax.swing.JLabel();
        CampoUsuarioR = new HintTextField("Crea tu usuario");
        jLabel2 = new javax.swing.JLabel();
        CampoEmailR = new HintTextField("Ingresa tu email");
        jLabel3 = new javax.swing.JLabel();
        CampoPasswordR = new HintPasswordField("Crea tu contraseña");
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro De Cuenta");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegistro.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabelRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistro.setText("Registrese");
        getContentPane().add(jLabelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 25, 300, 62));

        CampoUsuarioR.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        getContentPane().add(CampoUsuarioR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 210, 40));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/advertencia.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 30, 40));

        CampoEmailR.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        getContentPane().add(CampoEmailR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, 40));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/advertencia.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 30, 40));

        CampoPasswordR.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        getContentPane().add(CampoPasswordR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 210, 40));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/advertencia.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 30, 40));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/advertencia.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 30, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iniciar-sesion.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, 70));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 30, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo1(1).png"))); // NOI18N
        Fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FondoMouseClicked(evt);
            }
        });
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        JOptionPane.showMessageDialog(null, "En este campo debe crear su Usuario");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        JOptionPane.showMessageDialog(null, "En este campo debe ingresar su correo elecronico\n(Para recuperar su contraseña en caso de que se le olvide)");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        JOptionPane.showMessageDialog(null, "En este campo debe crear su contraseña\n(Para iniciar sesion)");
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        JOptionPane.showMessageDialog(null, "Pulse el boton para registrarse exitosamente e ir a la pestaña de inicio\n(Para que inicie sesion en su nueva cuenta)");
    }//GEN-LAST:event_jLabel5MouseClicked

    private void FondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMouseClicked

    }//GEN-LAST:event_FondoMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Validacion o = new Validacion();
        String usuario = CampoUsuarioR.getText();
        String correo = CampoEmailR.getText();
        char[] contrasena = CampoPasswordR.getPassword();
        String contrasenaTexto = new String(contrasena);
        if (usuario.isEmpty() || correo.isEmpty() || contrasenaTexto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos", "faltan campos por llenar", 0);
        } else if (!esContrasenaValida(contrasenaTexto)) {
            JOptionPane.showMessageDialog(null, "La contraseña debe tener al menos 8 caracteres y contener al menos una letra y un número");
        } else if (!o.VerificarMail(correo)) {
            JOptionPane.showMessageDialog(null, "Ingrese un correo elecronico valido", "correo no valido", 0);
        } else {
            // Solicitar al usuario la ruta de almacenamiento y el nombre del archivo .txt
            JOptionPane.showMessageDialog(this, "cuando el proceso termine se abrira una ventana\nen donde debera elegir donde se almacenara el archivo con sus datos\n(El archivo debe ser extension .txt)");
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos txt", "txt"));
            int seleccion = fileChooser.showSaveDialog(this);

            if (seleccion == JFileChooser.APPROVE_OPTION) {
                File archivo = fileChooser.getSelectedFile();
                String rutaArchivo = archivo.getAbsolutePath();
                if (archivo != null) {
                    if (archivo.exists()) {
                        // Mostrar un mensaje de error
                        JOptionPane.showMessageDialog(this, "El archivo ya existe", "Error", 0);
                    } else {
                        // Almacenar los datos de registro en el archivo .txt
                        try {
                            FileWriter escritor = new FileWriter(rutaArchivo, true);

                            escritor.write("Usuario: " + usuario + "\n");
                            escritor.write("Correo: " + correo + "\n");
                            escritor.write("Contraseña: " + contrasena + "\n");

                            escritor.close();
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        }

                        // Mostrar un mensaje de éxito
                        JOptionPane.showMessageDialog(this, "Datos almacenados correctamente");
                        Login obj = new Login();
                        obj.setVisible(true);
                        SingUp.this.dispose();
                    }
                } else {
                    // Mostrar un mensaje de error
                    JOptionPane.showMessageDialog(this, "No se seleccionó ningún archivo", "Error", 0);
                }

            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked
    public boolean esContrasenaValida(String contrasena) {
        if (contrasena.length() < 8) {
            return false;
        }
        boolean tieneLetra = false;
        boolean tieneNumero = false;
        for (int i = 0; i < contrasena.length(); i++) {
            char c = contrasena.charAt(i);
            if (Character.isLetter(c)) {
                tieneLetra = true;
            } else if (Character.isDigit(c)) {
                tieneNumero = true;
            }
        }
        return tieneLetra && tieneNumero;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoEmailR;
    private javax.swing.JPasswordField CampoPasswordR;
    private javax.swing.JTextField CampoUsuarioR;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelRegistro;
    // End of variables declaration//GEN-END:variables
}
